[package]
name = "fractaller"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Shapur <48966182+Shapur1234@users.noreply.github.com>"]
repository = "https://github.com/Shapur1234/Fractaller"

[dependencies]
instant = "0.1.12"
rayon = "1.8.0"
softbuffer = { git = "https://github.com/rust-windowing/softbuffer" }
winit = "0.29"


[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
  "Document",
  "Window",
  "Element",
  "Location",
] }

[workspace]
members = ["run-wasm"]
