[package]
name = "fractaller"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Shapur <48966182+Shapur1234@users.noreply.github.com>"]
repository = "https://github.com/Shapur1234/Fractaller"

[dependencies]
