[package]
name = "fractaller"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Shapur <48966182+Shapur1234@users.noreply.github.com>"]
repository = "https://github.com/Shapur1234/Fractaller"

[dependencies]
cgmath = "0.18.0"
console_error_panic_hook = "0.1.7"
num = "0.4.1"
softbuffer = { git = "https://github.com/rust-windowing/softbuffer" }
winit = "0.29"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.8.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"

[profile.release]
lto = true

[workspace]
members = ["run-wasm"]
