[package]
name = "fractaller"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Shapur <48966182+Shapur1234@users.noreply.github.com>"]
repository = "https://github.com/Shapur1234/Fractaller"

[workspace]
members = ["run-wasm"]

[profile.release]
lto = true

[dependencies]
cgmath = "0.18.0"
console_error_panic_hook = "0.1.7"
num = "0.4.1"
rayon = { version = "1.8.0", optional = true }
softbuffer = "0.4"
winit = "0.29"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
