[alias]
rr = "run --release --features rayon -- -C target-cpu=native"
r-wasm = "run --release --package run-wasm -- --package fractaller"
rr-wasm = "run --release --package run-wasm -- --package fractaller -- --release"
