[alias]
rr = "run --profile release-lto -- -C target-cpu=native"
r-wasm = "run --release --package run-wasm -- --package fractaller"
rr-wasm = "run --release --package run-wasm -- --package fractaller -- --profile release-lto"
